### ISSUE TITLE
Platform exception on health 

### ISSUE THREAD

**Issue by Goubeast** [cph-cachet/carp_studies_app#221]
Platform - Android simulator, SDK level 13

Throws a platform exception on accessing health service.

```
[log] [CAMS INFO] HealthServiceManager - Checking permissions for device of type: HealthService and id: Google Health Connect
E/MethodChannel#flutter_health( 7379): Failed to handle method call
E/MethodChannel#flutter_health( 7379): java.lang.IllegalArgumentException: Unsupported dataType: BASAL_ENERGY_BURNED
E/MethodChannel#flutter_health( 7379): 	at cachet.plugins.health.HealthPlugin.keyToHealthDataType(HealthPlugin.kt:443)
E/MethodChannel#flutter_health( 7379): 	at cachet.plugins.health.HealthPlugin.callToHealthTypes(HealthPlugin.kt:1302)
E/MethodChannel#flutter_health( 7379): 	at cachet.plugins.health.HealthPlugin.hasPermissions(HealthPlugin.kt:1352)
E/MethodChannel#flutter_health( 7379): 	at cachet.plugins.health.HealthPlugin.onMethodCall(HealthPlugin.kt:1536)
E/MethodChannel#flutter_health( 7379): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter_health( 7379): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_health( 7379): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_health( 7379): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_health( 7379): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter_health( 7379): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_health( 7379): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter_health( 7379): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter_health( 7379): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#flutter_health( 7379): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_health( 7379): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter_health( 7379): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by bardram** [comment]
Similar error when running on a phone that does not support Health Connect (SDK 28)

```
[log] [CAMS INFO] HealthServiceManager - Checking permissions for device of type: HealthService and id: Google Health Connect
[log] [CAMS INFO] WeatherServiceManager - Checking permissions for device of type: WeatherService and id: 12b6e28582eb9298577c734a31ba9f4f
E/MethodChannel#flutter_health( 7112): Failed to handle method call
E/MethodChannel#flutter_health( 7112): java.lang.IllegalArgumentException: Unsupported dataType: BASAL_ENERGY_BURNED
E/MethodChannel#flutter_health( 7112): 	at cachet.plugins.health.HealthPlugin.keyToHealthDataType(HealthPlugin.kt:443)
E/MethodChannel#flutter_health( 7112): 	at cachet.plugins.health.HealthPlugin.callToHealthTypes(HealthPlugin.kt:1302)
E/MethodChannel#flutter_health( 7112): 	at cachet.plugins.health.HealthPlugin.hasPermissions(HealthPlugin.kt:1352)
E/MethodChannel#flutter_health( 7112): 	at cachet.plugins.health.HealthPlugin.onMethodCall(HealthPlugin.kt:1536)
E/MethodChannel#flutter_health( 7112): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter_health( 7112): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_health( 7112): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_health( 7112): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_health( 7112): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#flutter_health( 7112): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_health( 7112): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#flutter_health( 7112): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/MethodChannel#flutter_health( 7112): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_health( 7112): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#flutter_health( 7112): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
